version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - mongo-data:/data/db
    networks:
      - tourism_net

  next-app:
    container_name: tourism-recommendations
    image: localhost:5005/tourism-recommendations
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        PORT: ${PORT}
        NEXT_PUBLIC_MONGODB_URI: ${NEXT_PUBLIC_MONGODB_URI}
        NEXT_PUBLIC_USP_KEY: ${NEXT_PUBLIC_USP_KEY}
    restart: always
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - .env
    volumes:
      - .env:/.env
    networks:
      - tourism_net
    depends_on:
      - mongo

volumes:
  mongo-data:

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  tourism_net:
    external: true
